### ISSUE TITLE
Bugi Listassa

### ISSUE THREAD

**Issue by ajh657** [jaakop/ticketApp#1]
kun lista tyhjennetään niin "Your place in the cue is" ei katoa ja jostain syystä sivu resetoi teksti fieldi resetoi  intervallilla.

![8tWbwVLPU4](https://user-images.githubusercontent.com/33629266/54430529-91195380-472c-11e9-91d5-802a112695f4.gif)

**Comment by jaakop** [comment]
Fixed the bug
